name: SPARTENX-OP

on:

    push:

    workflow_dispatch:

    

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

       - name: checkout chahat-music

         uses: actions/checkout@main

       

       - uses: styfle/cancel-workflow-action@0.9.0

         name: "cancel duplicate workflow runs"

         with:

            all_but_latest: true

            access_token: ${{ github.token }}

       - name: initialization chahat-music

         continue-on-error: true

         run: |

           git config --global user.name ${{ secrets.GIT_NAME }}

           git config --global user.email ${{ secrets.GIT_EMAIL }}

           git config --global credential.helper store

           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials

       - name: cloning repository

         continue-on-error: true

         run: |

           git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} chahat

       - name: running chahat-music server

         timeout-minutes: 350

         continue-on-error: true

         run: |

           cd chahat

           docker build . -t chahat

           docker run chahat

       - name: loop chahat-music server

         continue-on-error: true

         run: |

              git clone https://github.com/${GITHUB_REPOSITORY} loop

              cd loop || exit 1

              echo $(date -u +%T%P) >> loop.txt

              git add loop.txt

              git commit -m "SPARTENX-OP : Loop $(date -u +%D-%T%P)"

              git push -q https://${{ secrets.GIT_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:chahat-music

